CREATE TABLE IF NOT EXISTS users (
    UserID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
    Email VARCHAR(320) NOT NULL UNIQUE,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS password (
    UserID VARCHAR(128) PRIMARY KEY,
    Password VARCHAR(128) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES users (UserID) ON DELETE CASCADE
);