import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={
        inter.className + "bg-background text-text font-inter m-0 p-0"
      }>
      <Navbar />
      {children}
      </body>
    </html>
  );
}
